"""Write the genre vocabulary out as an ES module for the browser build.

The PKCE site has no server, so it runs its own port of the genre builder. The
bucketing rules are the part of that builder that changes -- a new Spotify
micro-genre means a new line in GENRE_ALIASES -- and a hand-maintained second
copy would drift the first time someone edited only one of them.

    python scripts/export_genre_aliases.py

The output is committed rather than generated at deploy time so that `docs/`
still works when opened directly, which is how the PKCE build is developed.
tests/test_genre_aliases_export.py fails if the committed file is stale.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.graph.builders.genre_network import (
    GENRE_ALIASES,
    UNCLASSIFIED,
    WEAK_ALIASES,
)

DESTINATION = ROOT / "docs" / "js" / "graph" / "genreAliases.js"

HEADER = """/**
 * Generated by scripts/export_genre_aliases.py -- do not edit.
 *
 * The single source of truth is GENRE_ALIASES in
 * app/graph/builders/genre_network.py, which explains what the rules mean and
 * which of them deliberately shadow each other. This file exists because the
 * PKCE build has no server to ask.
 */
"""


def _table(name: str, rules: dict[str, str]) -> str:
    entries = "\n".join(
        f"  {json.dumps(fragment)}: {json.dumps(bucket)},"
        for fragment, bucket in rules.items()
    )
    return f"export const {name} = {{\n{entries}\n}};\n"


def render() -> str:
    return (
        f"{HEADER}\n"
        f"{_table('GENRE_ALIASES', GENRE_ALIASES)}"
        f"\n{_table('WEAK_ALIASES', WEAK_ALIASES)}"
        f"\nexport const UNCLASSIFIED = {json.dumps(UNCLASSIFIED)};\n"
    )


def main() -> int:
    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    DESTINATION.write_text(render(), encoding="utf-8")
    print(
        f"Wrote {DESTINATION} — {len(GENRE_ALIASES)} rules, "
        f"{len(WEAK_ALIASES)} weak"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
